"""Command line for setup and inspection, without the web layer.

Deliberately imports nothing from ``app.api``: if this file ever needs FastAPI
to run, the core/adapter split has been broken. ``--check`` enforces that by
importing every core module.

    python -m app.cli --init-env              # first run: writes a working .env
    python -m app.cli --check
    python -m app.cli --search "落又一"
    python -m app.cli --add-user mai --password '...'
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


def _settings():
    from app.core.config import load_settings

    return load_settings()


def cmd_init_env(password: str, force: bool) -> int:
    """Write a .env that actually starts the app.

    The two required secrets have no sensible default — the app refuses to
    start without them on purpose — so the shortest honest path from `git
    clone` to a running app is to generate them here rather than to ask
    somebody to paste shell one-liners.
    """
    import secrets

    from app.core.config import ENV_FILE
    from app.core.users import MIN_PASSWORD_LEN, hash_password

    path = Path(ENV_FILE)
    if path.exists() and not force:
        print(f"{path} already exists. Move it aside, or pass --force to replace it.",
              file=sys.stderr)
        return 1

    if not password:
        import getpass

        password = getpass.getpass(f"Choose a password (min {MIN_PASSWORD_LEN}): ")
        if password != getpass.getpass("Repeat: "):
            print("Passwords do not match.", file=sys.stderr)
            return 1
    if len(password) < MIN_PASSWORD_LEN:
        print(f"Use at least {MIN_PASSWORD_LEN} characters.", file=sys.stderr)
        return 1

    path.write_text(
        f"""\
# Generated by `python -m app.cli --init-env`.
# Local defaults: serves the 10-item sample over plain HTTP.
# See .env.example for what every setting means.

AUTH_SECRET={secrets.token_urlsafe(48)}
APP_USERNAME=admin
APP_PASSWORD_HASH={hash_password(password)}

# 0 for plain HTTP. Set to 1 only when served over HTTPS — a Secure cookie is
# never sent over http, so 1 here makes login fail with no visible reason.
COOKIE_SECURE=0

# Only used when running without Docker; compose pins its own paths.
DATA_DIR=./data
DATASET_PATH=sample/dataset.jsonl
IMAGES_DIR=sample/images
""",
        encoding="utf-8",
    )
    print(f"wrote {path}")
    print("  username: admin")
    print("  password: the one you just chose")
    print()
    print("Now run:  uvicorn app.api.main:app --port 8000")
    print("Then open http://127.0.0.1:8000 and sign in as admin.")
    return 0


def cmd_hash_password(password: str) -> int:
    from app.core.users import hash_password

    if not password:
        import getpass

        password = getpass.getpass("Password: ")
        if password != getpass.getpass("Repeat: "):
            print("Passwords do not match.", file=sys.stderr)
            return 1
    if len(password) < 8:
        print("Use at least 8 characters.", file=sys.stderr)
        return 1
    print(hash_password(password))
    return 0


def _library():
    from app.core.dataset import Dataset
    from app.core.localimages import ImageLibrary

    settings = _settings()
    dataset = Dataset(settings.dataset_path)
    images = ImageLibrary(settings.images_dir)
    report = images.attach(dataset.items)
    return settings, dataset, report


def cmd_check() -> int:
    from app.core import dataset, localimages, models, users  # noqa: F401
    from app.core.config import describe_secrets

    settings, data, report = _library()
    print("core modules import cleanly (no web framework)")
    print(f"dataset       : {settings.dataset_path} ({'found' if data.exists else 'MISSING'})")
    print(f"images        : {settings.images_dir} ({'found' if report.exists else 'MISSING'})")
    print(f"rows          : {len(data.items)}"
          + (f"  ({data.malformed_lines} malformed lines skipped)"
             if data.malformed_lines else ""))
    print(f"image files   : {report.scanned}")
    print(f"matched       : {report.matched}")
    print(f"rows w/o image: {report.rows_without_image}")
    print(f"orphan images : {report.orphans}")
    print("secrets       : " + ", ".join(
        f"{k}={'set' if v else 'MISSING'}" for k, v in describe_secrets().items()
    ))

    missing = [k for k, v in describe_secrets().items() if not v]
    if missing:
        print(f"\nThe app will refuse to start: {', '.join(missing)} not set.")
        return 1
    return 0


def cmd_search(query: str, limit: int) -> int:
    _, data, _ = _library()
    page = data.search(query, limit=limit)
    print(f"{page.total} match(es) for {query!r}\n")
    for item in page.items:
        picture = item.image_name or "(NO IMAGE)"
        print(f"#{item.index + 1}  {picture}")
        if item.caption:
            print(f"    caption : {item.caption[:100]}")
        if item.ground_truth:
            print(f"    truth   : {item.ground_truth.splitlines()[0][:80]}")
        if item.post_url:
            print(f"    post    : {item.post_url}")
        print()
    return 0


def cmd_mismatch(limit: int) -> int:
    """List exactly what does not line up, for fixing at the source."""
    _, data, report = _library()
    missing = [i for i in data.items if not i.has_image]
    print(f"rows without an image ({len(missing)}):")
    for item in missing[:limit]:
        print(f"  #{item.index + 1}  {item.image or '(empty)'}")
    if len(missing) > limit:
        print(f"  … and {len(missing) - limit} more")

    print(f"\norphan images ({report.orphans}):")
    for name in sorted(report.orphan_images)[:limit]:
        print(f"  {name}")
    if report.orphans > limit:
        print(f"  … and {report.orphans - limit} more")
    return 0


def cmd_add_user(name: str, password: str, display: str, role: str) -> int:
    from app.core.users import UserError, UserStore

    settings = _settings()
    store = UserStore(
        settings.users_path, super_admin=os.environ.get("APP_USERNAME", "admin")
    )
    if not password:
        import getpass

        password = getpass.getpass("Password: ")
    try:
        user = store.create(name, password, role=role, display_name=display,
                            created_by="cli")
    except UserError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(f"created {user.username} ({user.role})")
    return 0


def cmd_stats() -> int:
    _, data, report = _library()
    print(json.dumps(
        {"dataset": data.stats(), "images": report.to_json()},
        indent=2, ensure_ascii=False,
    ))
    return 0


def main(argv: list[str] | None = None) -> int:
    from app.core.config import load_env_file

    # Everything this tool prints is Hán-Nôm, and a default Windows console is
    # not UTF-8 — without this even `--help` dies on a UnicodeEncodeError.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except (AttributeError, OSError, ValueError):
            pass

    load_env_file()

    parser = argparse.ArgumentParser(prog="app.cli", description=__doc__)
    parser.add_argument("--init-env", action="store_true",
                        help="generate a .env that starts the app")
    parser.add_argument("--force", action="store_true",
                        help="with --init-env, replace an existing .env")
    parser.add_argument("--check", action="store_true", help="verify configuration")
    parser.add_argument("--hash-password", action="store_true",
                        help="print a bcrypt hash for APP_PASSWORD_HASH")
    parser.add_argument("--stats", action="store_true", help="print dataset/image counts")
    parser.add_argument("--mismatch", action="store_true",
                        help="list rows without an image, and images without a row")
    parser.add_argument("--search", metavar="QUERY", default="")
    parser.add_argument("--add-user", metavar="NAME", default="")
    parser.add_argument("--password", default="")
    parser.add_argument("--display", default="")
    parser.add_argument("--role", default="reviewer", choices=["reviewer", "admin"])
    parser.add_argument("--limit", type=int, default=20)
    args = parser.parse_args(argv)

    if args.init_env:
        return cmd_init_env(args.password, args.force)
    if args.hash_password:
        return cmd_hash_password(args.password)
    if args.check:
        return cmd_check()
    if args.stats:
        return cmd_stats()
    if args.mismatch:
        return cmd_mismatch(args.limit)
    if args.search:
        return cmd_search(args.search, args.limit)
    if args.add_user:
        return cmd_add_user(args.add_user, args.password, args.display, args.role)

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
